"""empty message

Revision ID: 2e22f07f8359
Revises: 7616030e87a4
Create Date: 2022-02-17 16:27:37.412465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e22f07f8359'
down_revision = '7616030e87a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'word', type_='foreignkey')
    op.drop_column('word', 'word_log_id')
    op.add_column('word_log', sa.Column('word_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'word_log', 'word', ['word_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'word_log', type_='foreignkey')
    op.drop_column('word_log', 'word_id')
    op.add_column('word', sa.Column('word_log_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'word', 'word_log', ['word_log_id'], ['id'])
    # ### end Alembic commands ###
