"""empty message

Revision ID: 8e059f1c1596
Revises: 88bdd4abd16e
Create Date: 2022-02-08 18:12:52.056166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e059f1c1596'
down_revision = '88bdd4abd16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_nickname', table_name='user')
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.create_index('ix_user_nickname', 'user', ['nickname'], unique=False)
    # ### end Alembic commands ###
